# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardroom',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('boardroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Boardroom')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Slot'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set([('boardroom', 'slot', 'day')]),
        ),
    ]
