# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_questionnaire_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
