# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171205_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
