# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171205_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='naire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Questionnaire'),
        ),
    ]
